//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RipTrail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RipTrail.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rip Trail.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000004411434C.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Route.
        /// </summary>
        public static string EraseTrack {
            get {
                return ResourceManager.GetString("EraseTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackData.
        /// </summary>
        public static string LocalFolder {
            get {
                return ResourceManager.GetString("LocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationID.
        /// </summary>
        public static string MapApplicationID {
            get {
                return ResourceManager.GetString("MapApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationToken.
        /// </summary>
        public static string MapAuthenticationToken {
            get {
                return ResourceManager.GetString("MapAuthenticationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapCartographicMode.
        /// </summary>
        public static string MapCartographicMode {
            get {
                return ResourceManager.GetString("MapCartographicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MapSettings {
            get {
                return ResourceManager.GetString("MapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string MapTrack {
            get {
                return ResourceManager.GetString("MapTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Route.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Track.
        /// </summary>
        public static string SaveTrack {
            get {
                return ResourceManager.GetString("SaveTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCardFolder.
        /// </summary>
        public static string SDCardFolder {
            get {
                return ResourceManager.GetString("SDCardFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RipTrail-Backup.
        /// </summary>
        public static string SkyDriveFolder {
            get {
                return ResourceManager.GetString("SkyDriveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Location.
        /// </summary>
        public static string ToggleLocation {
            get {
                return ResourceManager.GetString("ToggleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserClearMapSave.
        /// </summary>
        public static string UserClearMapSave {
            get {
                return ResourceManager.GetString("UserClearMapSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc.
        /// </summary>
        public static string UserLocation {
            get {
                return ResourceManager.GetString("UserLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocConsent.
        /// </summary>
        public static string UserLocationConsent {
            get {
                return ResourceManager.GetString("UserLocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapUnits.
        /// </summary>
        public static string UserSettingsMapUnits {
            get {
                return ResourceManager.GetString("UserSettingsMapUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer.
        /// </summary>
        public static string UserSettingsOdometer {
            get {
                return ResourceManager.GetString("UserSettingsOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ZoomInText {
            get {
                return ResourceManager.GetString("ZoomInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ZoomOutText {
            get {
                return ResourceManager.GetString("ZoomOutText", resourceCulture);
            }
        }
    }
}
